# 临时测试配置 - 演示环境变量直接绑定
app:
  name: "TaskManage"
  version: "1.0.0"
  environment: "production"
  debug: false

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

database:
  driver: "mysql"
  host: "localhost"  # 这里先用固定值演示
  port: 3306
  username: "taskmanage"
  password: "taskmanage123"
  database: "taskmanage_prod"
  charset: "utf8mb4"
  max_idle_conns: 20
  max_open_conns: 200
  conn_max_lifetime: 7200

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  max_retries: 5
  pool_size: 20
  min_idle_conn: 10

jwt:
  secret: "production-jwt-secret-key-at-least-32-characters-long-secure"
  access_token_ttl: 1800
  refresh_token_ttl: 259200
  issuer: "taskmanage"
  refresh_threshold: 900

asynq:
  redis_addr: "localhost:6379"
  redis_password: ""
  redis_db: 1
  concurrency: 20
  queues:
    critical: 10
    default: 6
    low: 4

log:
  level: "info"
  format: "json"
  output: "stdout"  # 改为stdout便于测试
  filename: "/var/log/taskmanage/app.log"
  max_size: 200
  max_backups: 10
  max_age: 30
  compress: true
