# 生产环境配置
app:
  name: "TaskManage"
  version: "1.0.0"
  environment: "production"
  debug: false

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

database:
  driver: "mysql"
  host: "${DB_HOST}"
  port: 3306
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  database: "${DB_NAME}"
  charset: "utf8mb4"
  max_idle_conns: 20
  max_open_conns: 200
  conn_max_lifetime: 7200

redis:
  host: "${REDIS_HOST}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  database: 0
  max_retries: 5
  pool_size: 20
  min_idle_conn: 10

jwt:
  secret: ""
  access_token_ttl: 1800    # 30分钟
  refresh_token_ttl: 259200 # 3天
  issuer: "taskmanage"
  refresh_threshold: 900    # 15分钟

asynq:
  redis_addr: "${REDIS_HOST}:6379"
  redis_password: "${REDIS_PASSWORD}"
  redis_db: 1
  concurrency: 20
  queues:
    critical: 10
    default: 6
    low: 4

log:
  level: "info"
  format: "json"
  output: "file"
  filename: "/var/log/taskmanage/app.log"
  max_size: 200
  max_backups: 10
  max_age: 30
  compress: true
