# 测试环境配置
app:
  name: "TaskManage-Test"
  version: "1.0.0"
  environment: "testing"
  debug: true

server:
  host: "localhost"
  port: 8081
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "test_user"
  password: "test_password"
  database: "taskmanage_test"
  charset: "utf8mb4"
  max_idle_conns: 2
  max_open_conns: 10
  conn_max_lifetime: 1800

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 2
  max_retries: 2
  pool_size: 3
  min_idle_conn: 1

jwt:
  secret: "test-jwt-secret-key-for-testing-only-32chars"
  access_token_ttl: 300     # 5分钟 (测试环境短一些)
  refresh_token_ttl: 3600   # 1小时
  issuer: "taskmanage-test"
  refresh_threshold: 150    # 2.5分钟

asynq:
  redis_addr: "localhost:6379"
  redis_password: ""
  redis_db: 3
  concurrency: 2
  queues:
    critical: 1
    default: 1
    low: 1

log:
  level: "debug"
  format: "text"
  output: "stdout"
  filename: "logs/test.log"
  max_size: 10
  max_backups: 1
  max_age: 1
  compress: false
